# Generated by Django 3.2.7 on 2021-09-18 05:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('top', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='name',
        ),
    ]
