# Generated by Django 3.2.7 on 2021-09-27 04:41

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('top', '0002_alter_problems_contributor'),
    ]

    operations = [
        migrations.CreateModel(
            name='submissionA',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dimensions', models.IntegerField()),
                ('Solution', models.TextField()),
                ('Score', models.IntegerField()),
                ('time', models.TimeField()),
                ('submissionDesc', models.TextField()),
                ('question_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='top.problems')),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
