# Generated by Django 3.2.7 on 2021-10-05 00:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('top', '0005_remove_submission_submissiondesc'),
    ]

    operations = [
        migrations.RenameField(
            model_name='problem',
            old_name='question_id',
            new_name='id',
        ),
    ]
