# Generated by Django 3.2.7 on 2021-11-08 12:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('top', '0006_rename_question_id_problem_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='problem',
            old_name='id',
            new_name='question_id',
        ),
    ]
