# Generated by Django 3.2.5 on 2021-09-16 06:38

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='user_datas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=50)),
                ('email', models.CharField(max_length=50)),
                ('name', models.CharField(max_length=50)),
                ('age', models.CharField(max_length=50)),
                ('user_field', models.CharField(max_length=50)),
                ('user_profession', models.CharField(max_length=50)),
                ('user_university', models.CharField(max_length=50)),
                ('password', models.CharField(max_length=200)),
                ('password2', models.CharField(max_length=200)),
            ],
        ),
    ]
